# Generated by Django 3.2 on 2024-10-24 12:20

from django.db import migrations, models
import titles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[titles.validators.valid_date], verbose_name='Год выпуска'),
        ),
    ]
